// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CosmeticsStore.Repositories.Models;

[Table("CosmeticInformation")]
public partial class CosmeticInformation
{
    [Key]
    [Column("CosmeticID")]
    [StringLength(30)]
    public string CosmeticId { get; set; }

    [Required]
    [StringLength(80, MinimumLength = 2)]
    [RegularExpression(@"^([A-Z][a-zA-Z0-9@#]*\s?)+$")]
    public string CosmeticName { get; set; }

    [Required]
    [StringLength(80, MinimumLength = 2)]
    public string SkinType { get; set; }

    [Required]
    [StringLength(160)]
    public string ExpirationDate { get; set; }

    [Required]
    [StringLength(400)]
    public string CosmeticSize { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    [Range(0, double.MaxValue)]
    public decimal DollarPrice { get; set; }

    [Column("CategoryID")]
    [StringLength(30)]
    public string CategoryId { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("CosmeticInformations")]
    public virtual CosmeticCategory Category { get; set; }
}