// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cosmetic.Repositories.Models;

[Table("CosmeticCategory")]
public partial class CosmeticCategory
{
    [Key]
    [Column("CategoryID")]
    [StringLength(30)]
    public string CategoryId { get; set; }

    [Required]
    [StringLength(120)]
    public string CategoryName { get; set; }

    [Required]
    [StringLength(250)]
    public string UsagePurpose { get; set; }

    [Required]
    [StringLength(250)]
    public string FormulationType { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<CosmeticInformation> CosmeticInformations { get; set; } = new List<CosmeticInformation>();
}