// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SCBS.BlazorApp.Clients.Models;

[Table("User")]
public partial class User
{
    [Key]
    [Column("ID")]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Username { get; set; }

    [Required]
    [StringLength(50)]
    public string FullName { get; set; }

    [Required]
    [StringLength(180)]
    public string Password { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(255)]
    public string Avatar { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [Required]
    [StringLength(7)]
    public string Gender { get; set; }

    [Required]
    [StringLength(8)]
    public string Role { get; set; }

    [Required]
    [StringLength(8)]
    public string Status { get; set; }

    public double? Rating { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}