// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using Microsoft.EntityFrameworkCore;

namespace SCBS.SoapApiServices.SoapModels;

[DataContract]
public partial class Schedule
{
    [DataMember]
    public Guid Id { get; set; }
    [DataMember]
    public Guid UserId { get; set; }
    [DataMember]
    public DateTime WorkDate { get; set; }
    [DataMember]
    public string Status { get; set; }
    [DataMember]
    public DateTime? CreatedAt { get; set; }
    [DataMember]
    public DateTime? UpdatedAt { get; set; }
    [DataMember]
    public string Title { get; set; }
    [DataMember]
    public string Description { get; set; }
    [DataMember]
    public string Location { get; set; }
    [DataMember]
    public string Notes { get; set; }
    [DataMember]
    public virtual User User { get; set; }
}