// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using Microsoft.EntityFrameworkCore;

namespace SCBS.SoapApiServices.SoapModels;

[DataContract]
public partial class User
{
    [DataMember]
    public Guid Id { get; set; }
    [DataMember]
    public string Username { get; set; }
    [DataMember]
    public string FullName { get; set; }
    [DataMember]
    public string Password { get; set; }
    [DataMember]
    public string Email { get; set; }
    [DataMember]
    public string Avatar { get; set; }
    [DataMember]
    public string Phone { get; set; }
    [DataMember]
    public string Gender { get; set; }
    [DataMember]
    public string Role { get; set; }
    [DataMember]
    public string Status { get; set; }
    [DataMember]
    public double? Rating { get; set; }
    [DataMember]
    public DateTime? CreatedAt { get; set; }
    [DataMember]
    public DateTime? UpdatedAt { get; set; }
    [DataMember]
    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}