//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBSWCFServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://schemas.datacontract.org/2004/07/SCBS.SoapApiServices.SoapModels")]
    public partial class Schedule : object
    {
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private string DescriptionField;
        
        private System.Guid IdField;
        
        private string LocationField;
        
        private string NotesField;
        
        private string StatusField;
        
        private string TitleField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private SCBSWCFServiceReference.User UserField;
        
        private System.Guid UserIdField;
        
        private System.DateTime WorkDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCBSWCFServiceReference.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WorkDate
        {
            get
            {
                return this.WorkDateField;
            }
            set
            {
                this.WorkDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SCBS.SoapApiServices.SoapModels")]
    public partial class User : object
    {
        
        private string AvatarField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private string EmailField;
        
        private string FullNameField;
        
        private string GenderField;
        
        private System.Guid IdField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private System.Nullable<double> RatingField;
        
        private string RoleField;
        
        private SCBSWCFServiceReference.Schedule[] SchedulesField;
        
        private string StatusField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avatar
        {
            get
            {
                return this.AvatarField;
            }
            set
            {
                this.AvatarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCBSWCFServiceReference.Schedule[] Schedules
        {
            get
            {
                return this.SchedulesField;
            }
            set
            {
                this.SchedulesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SCBSWCFServiceReference.IScheduleSoapService")]
    public interface IScheduleSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleSoapService/GetSchedules", ReplyAction="http://tempuri.org/IScheduleSoapService/GetSchedulesResponse")]
        System.Threading.Tasks.Task<SCBSWCFServiceReference.Schedule[]> GetSchedulesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleSoapService/GetSchedule", ReplyAction="http://tempuri.org/IScheduleSoapService/GetScheduleResponse")]
        System.Threading.Tasks.Task<SCBSWCFServiceReference.Schedule> GetScheduleAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleSoapService/CreateSchedule", ReplyAction="http://tempuri.org/IScheduleSoapService/CreateScheduleResponse")]
        System.Threading.Tasks.Task<int> CreateScheduleAsync(SCBSWCFServiceReference.Schedule Schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleSoapService/UpdateSchedule", ReplyAction="http://tempuri.org/IScheduleSoapService/UpdateScheduleResponse")]
        System.Threading.Tasks.Task<int> UpdateScheduleAsync(SCBSWCFServiceReference.Schedule Schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleSoapService/DeleteSchedule", ReplyAction="http://tempuri.org/IScheduleSoapService/DeleteScheduleResponse")]
        System.Threading.Tasks.Task<bool> DeleteScheduleAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleSoapService/GetUsers", ReplyAction="http://tempuri.org/IScheduleSoapService/GetUsersResponse")]
        System.Threading.Tasks.Task<SCBSWCFServiceReference.User[]> GetUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IScheduleSoapServiceChannel : SCBSWCFServiceReference.IScheduleSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ScheduleSoapServiceClient : System.ServiceModel.ClientBase<SCBSWCFServiceReference.IScheduleSoapService>, SCBSWCFServiceReference.IScheduleSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ScheduleSoapServiceClient() : 
                base(ScheduleSoapServiceClient.GetDefaultBinding(), ScheduleSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IScheduleSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScheduleSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ScheduleSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), ScheduleSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScheduleSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ScheduleSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScheduleSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ScheduleSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScheduleSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SCBSWCFServiceReference.Schedule[]> GetSchedulesAsync()
        {
            return base.Channel.GetSchedulesAsync();
        }
        
        public System.Threading.Tasks.Task<SCBSWCFServiceReference.Schedule> GetScheduleAsync(string id)
        {
            return base.Channel.GetScheduleAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CreateScheduleAsync(SCBSWCFServiceReference.Schedule Schedule)
        {
            return base.Channel.CreateScheduleAsync(Schedule);
        }
        
        public System.Threading.Tasks.Task<int> UpdateScheduleAsync(SCBSWCFServiceReference.Schedule Schedule)
        {
            return base.Channel.UpdateScheduleAsync(Schedule);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteScheduleAsync(string id)
        {
            return base.Channel.DeleteScheduleAsync(id);
        }
        
        public System.Threading.Tasks.Task<SCBSWCFServiceReference.User[]> GetUsersAsync()
        {
            return base.Channel.GetUsersAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IScheduleSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IScheduleSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7230/SCBSSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ScheduleSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IScheduleSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ScheduleSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IScheduleSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IScheduleSoapService,
        }
    }
}
